export interface Card {
	id: string; // e.g., "spades-A"
	suit: '♠' | '♥' | '♦' | '♣';
	value: string;
	suitName: 'spades' | 'hearts' | 'diamonds' | 'clubs';
	color: 'red' | 'black';
}

export interface Player {
	id: string; // unique playerId generated by client
	name: string;
	color: string; // Avatar hex color code
	hand: Card[];
	reserveStack: Card[]; // trick cards won in Phase 1
	isDone: boolean; // escaped hand in Phase 2
	isSkitgubbe: boolean; // loser flag
	isHost: boolean; // host flag
	inviteStatus?: 'pending' | 'accepted';
	isBot?: boolean;
	avatarConfig?: string;
	isSweetgubbe?: boolean;
	isTrumfman?: boolean;
	isConstipated?: boolean;
	isMegaConstipated?: boolean;
}

export interface GameState {
	status: 'waiting' | 'playing' | 'ended';
	phase: 1 | 2;
	activePlayerIdx: number;
	players: Player[];
	deck: Card[];
	tablePile: Card[][]; // array of play batches
	tablePilePlayers: string[]; // player IDs matching tablePile batches
	discardPile: Card[]; // burned cards
	trumpCard: Card | null;
	hiddenTrumpStorage: { playerId: string; card: Card } | null;
	logs: string[];
	tieBreakerActive: boolean;
	tiedPlayerIds: string[];
	tieBreakerStartPileSize: number;
	trickWinnerId: string | null;
	seq?: number;
}

// Client -> Server messages
export type ClientMessage =
	| { type: 'join'; playerId: string; name: string; color: string; lastSeq?: number }
	| { type: 'startGame' }
	| { type: 'playCards'; cardIds: string[]; debugForce?: boolean }
	| { type: 'pickUp'; debugForce?: boolean }
	| { type: 'chance'; debugForce?: boolean }
	| { type: 'sprinkle'; cardIds: string[] }
	| { type: 'resetGame' }
	| { type: 'debugSkipToPhase2' };

// Server -> Client messages
export type ServerMessage =
	| { type: 'stateUpdate'; state: GameState; yourPlayerId: string }
	| { type: 'replay'; states: GameState[]; yourPlayerId: string }
	| { type: 'error'; message: string };

