// CRITICAL: changing these arrays changes the on-disk card encoding and breaks all persisted games.
export const VALUES_ORDER = [
	'2',
	'3',
	'4',
	'5',
	'6',
	'7',
	'8',
	'9',
	'10',
	'J',
	'Q',
	'K',
	'A'
] as const;
export const SUITS_ORDER = ['spades', 'hearts', 'diamonds', 'clubs'] as const;

export type CardValue = (typeof VALUES_ORDER)[number];
export type SuitName = (typeof SUITS_ORDER)[number];
export type SuitSymbol = '♠' | '♥' | '♦' | '♣';
export type CardColor = 'red' | 'black';

interface CardBase {
	id: string; // e.g., "spades-A"
	suit: SuitSymbol;
	suitName: SuitName;
	color: CardColor;
}

// A real, face-known card. Rule logic (getValueNumeric, isValidPlay, …) only
// accepts these — masked cards must never reach it.
export interface Card extends CardBase {
	value: CardValue;
}

export const HIDDEN_CARD_VALUE = '?';

// A card whose face the recipient is not allowed to know: what the sanitizer
// puts in other players' hands, the deck and the discard pile on the wire.
// Same shape as Card so render code can treat both uniformly.
export interface MaskedCard extends CardBase {
	value: typeof HIDDEN_CARD_VALUE;
}

export type AnyCard = Card | MaskedCard;

export function isMasked(card: AnyCard | null | undefined): card is MaskedCard {
	return card?.value === HIDDEN_CARD_VALUE;
}

// Narrow a wire-state card list to the real cards in it. For the local
// player's own hand this is a type-level no-op (nothing there is masked).
export function realCards(cards: AnyCard[]): Card[] {
	return cards.filter((c): c is Card => !isMasked(c));
}

// C is Card for the server's master state and AnyCard for sanitized wire
// states, where hands/deck/discard may be masked. Table pile and trump are
// always face-up and stay Card.
export interface Player<C extends AnyCard = Card> {
	id: string; // unique playerId generated by client
	name: string;
	color: string; // Avatar hex color code
	hand: C[];
	reserveStack: C[]; // trick cards won in Phase 1
	isDone: boolean; // escaped hand in Phase 2
	isSkitgubbe: boolean; // loser flag
	isHost: boolean; // host flag
	inviteStatus?: 'pending' | 'accepted';
	hasLeft?: boolean; // left mid-game: shown grayed-out, skipped forever
	isOnline?: boolean;
	avatarConfig?: string;
	isSweetgubbe?: boolean;
	isTrumfman?: boolean;
	isConstipated?: boolean;
	isMegaConstipated?: boolean;
}

export interface GameState<C extends AnyCard = Card> {
	status: 'waiting' | 'playing' | 'ended';
	phase: 1 | 2;
	activePlayerIdx: number;
	players: Player<C>[];
	deck: C[];
	tablePile: Card[][]; // array of play batches (always face-up)
	tablePilePlayers: string[]; // player IDs matching tablePile batches
	discardPile: C[]; // burned cards
	trumpCard: Card | null;
	hiddenTrumpStorage: { playerId: string; card: C } | null;
	logs: string[];
	tieBreakerActive: boolean;
	tiedPlayerIds: string[];
	tieBreakerStartPileSize: number;
	trickWinnerId: string | null;
	// Set by applyChance, cleared by every other move; drives the client's
	// "card flies from the deck" animation. Always a face-up table card, so
	// it needs no masking in getSanitizedStateForPlayerId.
	lastChanceCardId?: string | null;
	seq?: number;
}

// What actually crosses the wire: a per-viewer state where cards the viewer
// may not see are MaskedCard.
export type SanitizedPlayer = Player<AnyCard>;
export type SanitizedGameState = GameState<AnyCard>;

// Client -> Server messages
export type ClientMessage =
	// playerId/name/color are IGNORED server-side: identity is the session
	// cookie verified at WS upgrade. They remain on the wire for compatibility.
	| { type: 'join'; playerId: string; name: string; color: string; lastSeq?: number }
	| { type: 'startGame' }
	| { type: 'playCards'; cardIds: string[]; debugForce?: boolean }
	| { type: 'pickUp'; debugForce?: boolean }
	| { type: 'chance'; debugForce?: boolean }
	| { type: 'sprinkle'; cardIds: string[] }
	| { type: 'resetGame' }
	| { type: 'debugSkipToPhase2' }
	| { type: 'debugForceLose' }
	| { type: 'chat'; message?: string; emote?: string };

export interface ChatMessage {
	id: number;
	playerId: string;
	message?: string;
	emote?: string;
	seq: number;
	createdAt: string;
}

// Server -> Client messages
export type ServerMessage =
	| { type: 'stateUpdate'; state: SanitizedGameState; yourPlayerId: string }
	| { type: 'replay'; states: SanitizedGameState[]; yourPlayerId: string }
	| ({ type: 'chatMessage' } & ChatMessage)
	| { type: 'chatHistory'; messages: ChatMessage[] }
	| { type: 'error'; message: string };
